/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import {
  getAllDataFromCollection,
  addDataToCollection,
} from './util/indexedDb';
import { fetchFromMongoDB } from './util/mongoDb';

clientsClaim();

const additionalResourcesToCache = [
  { url: 'favicon.ico', revision: '1' },
  { url: 'service-worker.js', revision: null },
  { url: 'android-chrome-96x96.png', revision: '1' },
  { url: 'android-chrome-192x192.png', revision: '1' },
  { url: 'apple-touch-icon.png', revision: '1' },
  { url: 'browserconfig.xml', revision: '1' },
  { url: 'favicon-16x16.png', revision: '1' },
  { url: 'favicon-32x32.png', revision: '1' },
  { url: 'app.webmanifest', revision: '1' },
  { url: 'safari-pinned-tab.svg', revision: '1' },
  { url: 'mstile-150x150.png', revision: '1' },
];
// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST.concat(additionalResourcesToCache));

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-indexeddb') {
    event.waitUntil(syncIndexedDB());
  }
});
async function syncIndexedDB() {
  let req;
  try {
    const players = await getAllDataFromCollection('all_players');
    const games = await getAllDataFromCollection('all_games');
    const history = await getAllDataFromCollection('history');
    req = {
      //Endpunkt aktualisieren
      method: 'POST',
      body: JSON.stringify({ players, games, history }),
      headers: {
        'Content-Type': 'application/json',
      },
    };

    const response = await fetch(
      'https://lyra.et-inf.fho-emden.de:20112/_api/sync',
      req
    );

    const result = await response.json();
    console.log('Data synchronized:', result);
  } catch (error) {
    console.error('Sync failed:', error, req);
  }
}

// Funktion zum Abrufen von Spielen aus der MongoDB und Speichern in der IndexedDB
async function cacheFromMongoDB(apiPoint, collection) {
  try {
    // Annahme: Hier ist eine Funktion oder ein API-Endpunkt zum Abrufen der Spiele aus der MongoDB
    const dataFromMongoDB = await fetchFromMongoDB(apiPoint);
    await dataFromMongoDB.forEach((element) => {
      addDataToCollection(element, collection);
    });
    // Speichere die Spiele in der IndexedDB
  } catch (error) {
    console.error('Error caching games from MongoDB:', error);
    throw error;
  }
}

// Installationsereignis des Service Workers
self.addEventListener('install', (event) => {
  event.waitUntil(
    Promise.all([
      cacheFromMongoDB('games', 'all_games'),
      cacheFromMongoDB('players', 'all_players'),
      cacheFromMongoDB('history', 'history'),
    ])
  );
});
// Any other custom service worker logic can go here.
